# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_by', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('phase', models.CharField(blank=True, max_length=25, null=True)),
                ('expected', models.DateTimeField(null=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_by', models.CharField(max_length=100, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Block')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_by', models.CharField(max_length=100, null=True)),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Drawing')),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.DrawingStatus'),
        ),
    ]
