# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20160119_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
