# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20160119_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
