# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_drawing_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to=tracking.models.drawing_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='attachments',
        ),
        migrations.AddField(
            model_name='drawingattachment',
            name='drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Drawing'),
        ),
    ]
