# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_drawingattachment_mod_by'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='drawingattachment',
        #     name='add_date',
        #     field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 20, 21, 2, 38, 780105, tzinfo=utc)),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='drawingattachment',
        #     name='mod_date',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
    ]
