# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20160120_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='revision',
        ),
        migrations.AddField(
            model_name='comment',
            name='revision',
            field=models.ManyToManyField(to='tracking.Revision'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Project'),
        ),
    ]
