# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_phase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='phase',
            new_name='phasechar',
        ),
    ]
