# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20160122_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Phase'),
        ),
    ]
