# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_remove_drawing_phasechar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='block',
            new_name='oldblock',
        ),
    ]
