# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_auto_20160122_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='block',
            field=models.ManyToManyField(to='tracking.Block'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='oldblock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldblock', to='tracking.Block'),
        ),
    ]
