# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_auto_20160122_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='oldblock',
        ),
    ]
