# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0017_remove_drawing_oldblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to=tracking.models.drawing_upload_path)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Comment')),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to=tracking.models.drawing_upload_path)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, upload_to=tracking.models.drawing_upload_path)),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('mod_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.Revision')),
            ],
        ),
    ]
