# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_commentattachment_replyattachment_revisionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
