# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_reply_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentattachment',
            old_name='comment',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='drawingattachment',
            old_name='drawing',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='replyattachment',
            old_name='reply',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='revisionattachment',
            old_name='revision',
            new_name='link',
        ),
    ]
