# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20160126_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='file_cat',
            field=models.CharField(default='comment', max_length=15),
        ),
        migrations.AddField(
            model_name='drawingattachment',
            name='file_cat',
            field=models.CharField(default='drawing', max_length=15),
        ),
        migrations.AddField(
            model_name='replyattachment',
            name='file_cat',
            field=models.CharField(default='reply', max_length=15),
        ),
        migrations.AddField(
            model_name='revisionattachment',
            name='file_cat',
            field=models.CharField(default='revision', max_length=15),
        ),
    ]
