# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_drawingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingsubscription',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
