# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0023_drawingsubscription_mod_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawingsubscription',
            old_name='mod_date',
            new_name='last_mod_date',
        ),
        migrations.AddField(
            model_name='drawingsubscription',
            name='last_mod_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawingsubscription',
            name='mod_info',
            field=models.CharField(default='n/a', max_length=250),
        ),
        migrations.AlterField(
            model_name='drawingsubscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
